### ISSUE TITLE
Agent throws ConnectionClosedException when fetching agent commands

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#1131]
In certain circumstances, the agent throws an exception when trying to fetch new agent commands.

```
org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
        at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:263)
        at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:222)
        at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:183)
        at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:210)
        at org.apache.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:312)
        at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:142)
        at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
        at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._closeInput(UTF8StreamJsonParser.java:228)
        at com.fasterxml.jackson.core.base.ParserBase.close(ParserBase.java:368)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4021)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070)
        at rocks.inspectit.ocelot.core.command.CommandHandler.processHttpResponse(CommandHandler.java:124)
        at rocks.inspectit.ocelot.core.command.CommandHandler.nextCommand(CommandHandler.java:73)
        at rocks.inspectit.ocelot.core.command.CommandHandler.nextCommand(CommandHandler.java:57)
        at rocks.inspectit.ocelot.core.command.AgentCommandService.run(AgentCommandService.java:93)
```

It looks like that the connection is closed before the respones was fully received?

**Comment by mariusoe** [comment]
See the following ticket for a similar problem: https://github.com/eclipse-ee4j/jersey/issues/3629
