### ISSUE TITLE
[Bug] - CRITICAL: Deadlock AgentHealthManager and failing instrumentation

### ISSUE THREAD

**Issue by matthias-huber** [inspectIT/inspectit-ocelot#1597]
**Describe the bug**
Under unknown circumstances an inspectIT Thread as well as an application thread run into a deadlock.
The inspectIT Thread tries to log a message in AgentHealthManager and the application thread wants to log an error from a failing instrumentation (ContextPropagationUtil.readPropagatedSpanContextFromHeaderMap). Afterwards each thread that also runs into an failing instrumentation is also blocked as the log cannot be written. Finally, the application crashes or is not capable to respond if too many threads are blocked.

How I interpret the thread dump (section Additional information):
- inspectIT Thread: AgentHealthManager.triggerEventAndMetricIfHealthChanged detects a AgentHealtStatus Change (maybe because the instrumentation failed). Within this method, a lock is created 0x000000030a72ce78 and the thread wants to write a log. Unfortunately, the application thread already acquired the lock
- Application Thread: The failing instrumentation triggers writing of an error lock. Logback creates a Lock (the lock that the inspectIT Agent cannot get). Afterwards Logback calls rocks.inspectit.ocelot.core.logging.logback.InternalProcessingAppender.append that calls AgentHealthManager.triggerEventAndMetricIfHealthChanged. As the inspectIT Thread holds the lock to the synchronize block, the application thread is blocked

AgentHealthManager.triggerEventAndMetricIfHealthChanged

**To Reproduce**
Don't know how to reproduce

**Expected behavior**
No deadlock ;-) Both threads can write the log.
I think best would be that the application thread is decoupled from "Agent Status Health", meaning detection, signaling should not happen within the application thread. It should not happen that managing the Agent Health Status can decrease application performance until application outage

**Additional information (screenshots, stack traces, etc.)**

`Found one Java-level deadlock:
=============================
"inspectit-thread-0":
  waiting to lock monitor 0x00007f1a5bbee480 (object 0x000000030dc40a88, a rocks.inspectit.ocelot.core.logging.logback.InternalProcessingAppender),
  which is held by "http-nio-8080-exec-1447"
"http-nio-8080-exec-1447":
  waiting to lock monitor 0x00007f1a16c53b80 (object 0x000000030a72ce78, a rocks.inspectit.ocelot.core.selfmonitoring.AgentHealthManager),
  which is held by "inspectit-thread-0"

Java stack information for the threads listed above:
===================================================
"inspectit-thread-0":
	at ch.qos.logback.core.AppenderBase.doAppend(AppenderBase.java:63)
	- waiting to lock <0x000000030dc40a88> (a rocks.inspectit.ocelot.core.logging.logback.InternalProcessingAppender)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_2(Logger.java:414)
	at ch.qos.logback.classic.Logger.warn(Logger.java:700)
	at rocks.inspectit.ocelot.core.selfmonitoring.AgentHealthManager.triggerEventAndMetricIfHealthChanged(AgentHealthManager.java:168)
	- locked <0x000000030a72ce78> (a rocks.inspectit.ocelot.core.selfmonitoring.AgentHealthManager)
	at rocks.inspectit.ocelot.core.selfmonitoring.AgentHealthManager.checkHealthAndSchedule(AgentHealthManager.java:147)
	at rocks.inspectit.ocelot.core.selfmonitoring.AgentHealthManager$$Lambda$2107/0x0000000800c1ec40.run(Unknown Source)
	at rocks.inspectit.ocelot.core.instrumentation.context.ContextManager.lambda$wrap$1(ContextManager.java:76)
	at rocks.inspectit.ocelot.core.instrumentation.context.ContextManager$$Lambda$3174/0x0000000800dcec40.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.18/Executors.java:515)
	at java.util.concurrent.FutureTask.run(java.base@11.0.18/FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@11.0.18/ScheduledThreadPoolExecutor.java:304)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.18/Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.18/Unknown Source)
	at java.lang.Thread.run(java.base@11.0.18/Unknown Source)
"http-nio-8080-exec-1447":
	at rocks.inspectit.ocelot.core.selfmonitoring.AgentHealthManager.triggerEventAndMetricIfHealthChanged(AgentHealthManager.java:163)
	- waiting to lock <0x000000030a72ce78> (a rocks.inspectit.ocelot.core.selfmonitoring.AgentHealthManager)
	at rocks.inspectit.ocelot.core.selfmonitoring.AgentHealthManager.onLoggingEvent(AgentHealthManager.java:72)
	at rocks.inspectit.ocelot.core.logging.logback.InternalProcessingAppender.append(InternalProcessingAppender.java:76)
	at rocks.inspectit.ocelot.core.logging.logback.InternalProcessingAppender.append(InternalProcessingAppender.java:27)
	at ch.qos.logback.core.AppenderBase.doAppend(AppenderBase.java:82)
	- locked <0x000000030dc40a88> (a rocks.inspectit.ocelot.core.logging.logback.InternalProcessingAppender)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.error(Logger.java:538)
	at rocks.inspectit.ocelot.core.instrumentation.context.ContextPropagationUtil.readPropagatedSpanContextFromHeaderMap(ContextPropagationUtil.java:231)
	at rocks.inspectit.ocelot.core.instrumentation.context.InspectitContextImpl.readDownPropagationHeaders(InspectitContextImpl.java:468)
	at org.apache.tomcat.websocket.server.inspectitGen$$$5549193644763076326.executeImpl(VoidGenericActionTemplate.java)
	at org.apache.tomcat.websocket.server.inspectitGen$$$5549193644763076326.execute(VoidGenericActionTemplate.java:23)
	at rocks.inspectit.ocelot.core.instrumentation.actions.bound.BoundGenericAction.executeImpl(BoundGenericAction.java:113)
	at rocks.inspectit.ocelot.core.instrumentation.actions.bound.BoundGenericAction.execute(BoundGenericAction.java:100)
	at rocks.inspectit.ocelot.core.instrumentation.hook.actions.ConditionalHookAction.execute(ConditionalHookAction.java:24)
	at rocks.inspectit.ocelot.core.instrumentation.hook.MethodHook.onEnter(MethodHook.java:118)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	- locked <0x00000006490479a8> (a org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(java.base@11.0.18/Thread.java:829)
`

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
-

**Additional context**
Agent Version 2.3.0. Looking at Code Changes of AgentHealthManager and InternalProcessingAppender, I think it can happen since Version 1.16

**Comment by quandor** [comment]
I can reproduce the issue locally. Thanks for the bug report. That helped a lot by spotting the source of the bug. I should be able to have a fix at the end of the week.
But I am not so sure, when a release containing this fix will happen.
