### ISSUE TITLE
Fix Http PropertySource throwing errors on empty configuration

### ISSUE THREAD

**Issue by JonasKunz** [inspectIT/inspectit-ocelot#390]
When the configuration server respons with an empty body (=no configuration proeprties),
The Agent currently shows an error:
```
r.i.o.c.c.p.h.HttpPropertySourceState    : Could not parse fetched configuration.
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (ByteArrayInputStream); line: 1, column: 0]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4145)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3077)
        at rocks.inspectit.ocelot.core.config.util.PropertyUtils.readJsonFromStream(PropertyUtils.java:72)
        ... 11 common frames omitted
Wrapped by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (ByteArrayInputStream); line: 1, column: 0]
        at rocks.inspectit.ocelot.core.config.util.PropertyUtils.readJsonFromStream(PropertyUtils.java:78)
        at rocks.inspectit.ocelot.core.config.util.PropertyUtils.readJson(PropertyUtils.java:59)
        at rocks.inspectit.ocelot.core.config.propertysources.http.HttpPropertySourceState.parseProperties(HttpPropertySourceState.java:104)
        at rocks.inspectit.ocelot.core.config.propertysources.http.HttpPropertySourceState.update(HttpPropertySourceState.java:84)
        at rocks.inspectit.ocelot.core.config.propertysources.http.HttpConfigurationPoller.run(HttpConfigurationPoller.java:92)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:747)
```
We should add a simple check for this case.

**Comment by ravikamaraj** [comment]
Hi @JonasKunz 
I can help with this issue. Can you please let me know if I can pick this task

thanks

**Comment by JonasKunz** [comment]
Sure :)
I would suggest you add a check for an empty string / a string containing only whitespaces here:
https://github.com/inspectIT/inspectit-ocelot/blob/master/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpPropertySourceState.java#L103

Thank you!

**Comment by ravikamaraj** [comment]
@JonasKunz . thank you, that's good option.  Alternatively, we could add empty/blank check in [line no 82](https://github.com/inspectIT/inspectit-ocelot/blob/master/inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpPropertySourceState.java#L82). Kindly review and let me know your thoughts

**Comment by mariusoe** [comment]
Hi @ravikamaraj 

I think extending the null check (which you've linked) by also checking whether the string is blank or empty is a good solution for the problem because this way we can immediately skip all the parsing functionallity and continue.

**Comment by mariusoe** [comment]
Hi @ravikamaraj 

Jonas just mentioned that I missed a very important point and it will not be work as expected when doing the check on the line you mentioned and which I also thought. The reason is that when we skip the parsing of the properties in case the string is empty or blank, the existing properties will further be used. But the desired behavior is that the property source is empty in case an empty string is provided. For this it is the easiest way to return an empty `Properties` object when passing a blank string to the `parseProperties` method (the one Jonas mentioned).

**Comment by ravikamaraj** [comment]
thanks @mariusoe  for the clarification, will make the updates

**Comment by ravikamaraj** [comment]
updated the code per latest conversation. can you review [pr](https://github.com/inspectIT/inspectit-ocelot/pull/416). thanks
