### ISSUE TITLE
Code which is within Jigsaw-Modules can't be instrumented

### ISSUE THREAD

**Issue by JonasKunz** [inspectIT/inspectit-ocelot#474]
Instrumenting code which is within a Java 9 module leads to the following exception:
```
2019-11-29 12:23:35,804 DEBUG 4294   --- [inspectIT] [pectit-thread-1] r.i.o.c.i.injection.ClassInjector        : Injecting new class java.sql.inspectitGen$$$5325969431977122616
2019-11-29 12:23:35,805 ERROR 4295   --- [inspectIT] [pectit-thread-1] r.i.o.c.i.hook.MethodHookGenerator       : Failed to build action test_and_set_marker for data servicegraph_is_entry on method java.sql.Statement.executeUpdate, no value will be assigned
java.lang.IllegalAccessError: superinterface check failed: class java.sql.inspectitGen$$$5325969431977122616 (in module java.sql) cannot access class rocks.inspectit.ocelot.bootstrap.instrumentation.DoNotInstrumentMarker (in unnamed module @0x5c988252) because module java.sql does not read unnamed module @0x5c988252
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.System$2.defineClass(System.java:2123)
    at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(MethodHandles.java:962)
    at org.springframework.objenesis.instantiator.util.DefineClassHelper$Java11.defineClass(DefineClassHelper.java:129)
    ... 32 common frames omitted
Wrapped by: org.springframework.objenesis.ObjenesisException: java.sql.Statement has no permission to define the class
    at org.springframework.objenesis.instantiator.util.DefineClassHelper$Java11.defineClass(DefineClassHelper.java:131)
    at org.springframework.objenesis.instantiator.util.DefineClassHelper.defineClass(DefineClassHelper.java:143)
    at org.springframework.objenesis.instantiator.util.ClassDefinitionUtils.defineClass(ClassDefinitionUtils.java:91)
    at rocks.inspectit.ocelot.core.instrumentation.injection.ClassInjector.injectClass(ClassInjector.java:117)
    at rocks.inspectit.ocelot.core.instrumentation.injection.ClassInjector.inject(ClassInjector.java:97)
    at rocks.inspectit.ocelot.core.instrumentation.actions.GenericActionGenerator.lambda$getOrGenerateGenericAction$1(GenericActionGenerator.java:107)
    at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4717)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3444)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2193)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2152)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2042)
    ... 22 common frames omitted
Wrapped by: com.google.common.util.concurrent.UncheckedExecutionException: org.springframework.objenesis.ObjenesisException: java.sql.Statement has no permission to define the class
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2048)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3850)
    at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4712)
```

This exception is thrown when we try to define an action within the target module. The problem is that the bootstrap classes of Ocelot are loaded in an "unnamed" module, to which modulized classes do not have access by default.

The same exception will occur when we try to add an instrumentation hook to a method within a module.

This can be solved by calling the new `redefineModule` method ([javadoc](https://docs.oracle.com/javase/9/docs/api/java/lang/instrument/Instrumentation.html#redefineModule-java.lang.Module-java.util.Set-java.util.Map-java.util.Map-java.util.Set-java.util.Map-)).

We need to make sure that we give the target module access to the module containing our bootstrap-classes prior to injecting actions or performing instrumentation.

Note that this needs all to be done using reflection, as we want to maintain Java 8 compatibility.

**Comment by JonasKunz** [comment]
This exact error is actually a JVM bug:
https://bugs.openjdk.java.net/browse/JDK-8202408

However, in current state we will always at least the following type of warnings:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on org.springframework.objenesis.instantiator.util.DefineClassHelper$Java11 (file:/tmp/4208292638880112018.jar) to interface java.sql.PreparedStatement
WARNING: Please consider reporting this to the maintainers of org.springframework.objenesis.instantiator.util.DefineClassHelper$Java11
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Both can be avoided by using the redefineModule instrumentation method.
