### ISSUE TITLE
InternalError on Instrumentation.retransformClasses() of certain classes

### ISSUE THREAD

**Issue by mariusoe** [inspectIT/inspectit-ocelot#512]
On certain classes, espacially of the Spring framework, the JVM throwns an internal error when trying to retransform a class.

```
java.lang.InternalError: null
        at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
        at rocks.inspectit.ocelot.core.instrumentation.InstrumentationTriggerer.checkClassesForConfigurationUpdates(InstrumentationTriggerer.java:157)
        at rocks.inspectit.ocelot.core.service.BatchJobExecutorService.lambda$startJob$0(BatchJobExecutorService.java:126)
        at rocks.inspectit.ocelot.core.service.BatchJobExecutorService$BatchJob.lambda$new$0(BatchJobExecutorService.java:83)
        at rocks.inspectit.ocelot.core.instrumentation.correlation.log.LogTraceCorrelatorImpl.lambda$wrap$1(LogTraceCorrelatorImpl.java:64)
        at io.grpc.Context$1.run(Context.java:595)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:747)
```

In this case, a retransformation of the following class is causing the error: `'org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler'`

**Comment by mariusoe** [comment]
There is a similar problem on the OpenJDK bug tracker which is also related to retransforming Spring classes: [JDK-8220783 - InternalError on Instrumentation.retransformClasses()](https://bugs.openjdk.java.net/browse/JDK-8220783?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true)

The problem could be that the JVM throws a NoClassDefFoundError during link time.
This may be the case that some Spring classes are tried to be retransformed which are available but not used which dependencies are missing. But in that case, the classes should not be loaded in the first place.

**Comment by JonasKunz** [comment]
It seems like in certain environments (Java 1.8.0_252) this issue can also occure when old "actions" are redefined into new actions.

**Comment by mariusoe** [comment]
This problem can also occure when retransforming the class `org.quartz.ee.jta.JTAJobRunShell` using Java 1.8.0_242

**Comment by mariusoe** [comment]
This error can occure when classes are being lazy loaded by the JVM. In this case, when the agent tries to redefine a class it is internally using ByteBuddy to looking up existing methods and fields of that class. This is done so that method matchers can be used to target specific methods for instrumentation. The problem is that this lookup is using reflection which triggers the JVM to eagerly load the target class, leading to the problem that its dependencies are also resolved. In case these dependencies are not existing - because its a "optional dependency" - a NoClassDefFoundError will be thrown, leading to the log message shown in the ticket.
