### ISSUE TITLE
Span attributes are null since version 0.5

### ISSUE THREAD

**Issue by Alexander-Krause** [inspectIT/inspectit-ocelot#547]
I've used Ocelot 0.4 in the past. Today, I updated to version 0.6 and now spans do include their attributes, which are defined in the related ocelot configuration file. 

I found the following error for multiple instrumented classes and think it might be the cause (also in version 0.5):

```
2020-01-30 11:02:59,145 ERROR 8040   --- [inspectIT] [        Timer-0] r.i.o.c.instrumentation.hook.MethodHook  : Exit action Span Attribute Writing executed for method net.explorviz.sampleApplication.database.JDBCExample.runQueries threw an exception and from now on is disabled!
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at rocks.inspectit.ocelot.core.instrumentation.hook.VariableAccessorFactory.lambda$getSpecialVariableAccessor$5(VariableAccessorFactory.java:78)
	at rocks.inspectit.ocelot.core.instrumentation.hook.actions.span.WriteSpanAttributesAction.execute(WriteSpanAttributesAction.java:25)
	at rocks.inspectit.ocelot.core.instrumentation.hook.MethodHook.onExit(MethodHook.java:78)
	at net.explorviz.sampleApplication.database.JDBCExample.runQueries(JDBCExample.java:62)
	at net.explorviz.sampleApplication.database.JDBCExample.start(JDBCExample.java:27)
	at net.explorviz.sampleApplication.Main$DatabaseTask.run(Main.java:34)
	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
	at java.base/java.util.TimerThread.run(Unknown Source)
```

The error occurs in my demo setup, therefore, you can reproduce it:

1. Clone https://github.com/Alexander-Krause/ocelot-oc-playground
2. Start the `monitoringStack/docker-compose.yml` (make sure the collector is really started)
3. Start the `sampleApplication/runAppMonitoringWithOpenTracing.sh` script and check the command line.

**Comment by JonasKunz** [comment]
Thanks for your report!
The line throwing the exception is the following one:
```
return context -> context.getMethodArguments()[idx];
```
This code is responsible for extracting the method arguments for your instrumentation.

The `IndexOutOfBoundsException` states that you are trying to access an argument of the instrumented method which does not exist. E.g. In this case I suspect that `net.explorviz.sampleApplication.database.JDBCExample.runQueries` takes no arguments, but your instrumentation rule `trace_fibonacci` tries to extract the argument and place it as attribute on the trace.

The problem here is that your scope is not narrow enough: `fibonacci_scope` instruments *all* methods under the `net.explorviz.sampleApplication` package, not only your `fibonacci` method.
To solve this you can add a [method matcher](https://inspectit.github.io/inspectit-ocelot/docs/instrumentation/scopes#method-matcher) to your scope and also instrument only the class which declares the `fibonacci` method.

**Comment by Alexander-Krause** [comment]
That was the problem, thank you for the detailed explanation.
