### ISSUE TITLE
I am getting a lot of Exceptoins about "Error reading trace correlation data from the trace context headers."

### ISSUE THREAD

**Issue by martonsz** [inspectIT/inspectit-ocelot#938]
I am getting a lot of the following Exceptions in my logs (70 times per minute). Only the value after the string `Invalid tracestate: 420844@nr=0-0-420844-766593239.....` changes every time.

```
2020-10-09 03:28:54.584 [-version] u:0 ERROR r.i.o.c.i.c.ContextPropagationUtil [http-nio-8080-exec-4] Error reading trace correlation data from the trace context headers.
io.opencensus.trace.propagation.SpanContextParseException: Invalid tracestate: 420844@nr=0-0-420844-766593239-678ea8df4c2576d7-295999fbcd3f2a39-1-1.261772-1602206934509
	at io.opencensus.implcore.trace.propagation.TraceContextFormat.extract(TraceContextFormat.java:161)
	at rocks.inspectit.ocelot.core.instrumentation.context.ContextPropagationUtil.readPropagatedSpanContextFromHeaderMap(ContextPropagationUtil.java:190)
	at rocks.inspectit.ocelot.core.instrumentation.context.InspectitContextImpl.readDownPropagationHeaders(InspectitContextImpl.java:456)
	at javax.servlet.inspectitGen$$$1488179320945595566.executeImpl(VoidGenericActionTemplate.java)
	at javax.servlet.inspectitGen$$$1488179320945595566.execute(VoidGenericActionTemplate.java:23)
	at rocks.inspectit.ocelot.core.instrumentation.actions.bound.VoidDynamicBoundGenericAction.execute(VoidDynamicBoundGenericAction.java:27)
	at rocks.inspectit.ocelot.core.instrumentation.hook.actions.ConditionalHookAction.execute(ConditionalHookAction.java:24)
	at rocks.inspectit.ocelot.core.instrumentation.hook.MethodHook.onEnter(MethodHook.java:85)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at io.grpc.Context$1.run(Context.java:595)
	at io.grpc.Context$1.run(Context.java:595)
	at io.grpc.Context$1.run(Context.java:595)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Invalid key 420844@nr
	at io.opencensus.internal.Utils.checkArgument(Utils.java:67)
	at io.opencensus.trace.Tracestate$Entry.create(Tracestate.java:204)
	at io.opencensus.trace.Tracestate$Builder.set(Tracestate.java:129)
	at io.opencensus.implcore.trace.propagation.TraceContextFormat.extract(TraceContextFormat.java:156)
	... 31 common frames omitted
```

I have 8 other projects with identical setup and config. Only the project names differ. And they don't have this behavior.
I am not interested in instrumentation yet. I have set `inspectit.tracing.enabled` to `false`

Complete config

```
---
inspectit:
  service-name: REST
  tags:
    extra:
      'environment': production
  config.http.enabled: false
  exporters:
    metrics:
      prometheus:
        enabled: true
        port: 8081
    #tracing:
      #zipkin:
      #  url: http://zipkin-collector:9411/api/v2/spans
      #jaeger:
      #  url: http://jaeger-all-in-one:14268/api/traces
  logging:
    console:
      enabled: true
      pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS} [${deployVersion:-version}] trace:%X{traceid:-0} u:%X{uniqueId:-0} %-5level %logger{10} [%thread] %msg%n'
    file:
      enabled: false
  metrics:
    jmx:
      enabled: true
      lower-case-metric-name: true
      object-names:
        # allow-listed (true) and deny-listed (false) object names
        '[Catalina:type=Connector,port=8080]': true
        '[Catalina:type=GlobalRequestProcessor,name="http-nio-8080"]': true
        '[Catalina:type=Manager,host=localhost,*]': true
        '[Catalina:type=ThreadPool,name="http-nio-8080"]': true
        '[java.lang:type=GarbageCollector,*]': true
        '[java.lang:type=Memory]': true
        '[java.lang:type=OperatingSystem]': true
  tracing:
    enabled: false
    log-correlation:
      trace-id-mdc-injection:
        enabled: false # This causes memory leak alert in Tomcat.

  #instrumentation:
  #  scopes:
  #    's_gwt_remote_service':
  #      interfaces:
  #        - name: 'com.google.gwt.user.client.rpc.RemoteService'
  #          matcher-mode: EQUALS_FULLY
  #      type:
  #        - name: 'Impl'
  #          matcher-mode: ENDS_WITH
  #  rules:
  #    'r_gwt_remote_service_span':
  #      scopes:
  #        's_gwt_remote_service': true
  #      tracing:
  #        start-span: true
  #        #error-status: _thrown
  #    #'r_record_method_duration':
  #    #  scopes:
  #    #    's_gwt_remote_service': true
  #    #  tracing:
  #    #    start-span: true
```

# InspectIT info

I got these problems when I upgraded to InspectIT 1.5. I tried to upgrade to 1.6 but the Exceptions are still there.

```
2020-10-09 03:00:30,770 INFO  235    --- [inspectIT] [       Thread-0] rocks.inspectit.ocelot.core.AgentImpl    : Starting inspectIT Ocelot Agent...
2020-10-09 03:00:30,774 INFO  239    --- [inspectIT] [       Thread-0] rocks.inspectit.ocelot.core.AgentImpl    : 	Version: 1.6
2020-10-09 03:00:30,775 INFO  240    --- [inspectIT] [       Thread-0] rocks.inspectit.ocelot.core.AgentImpl    : 	Build Date: Fri Oct 02 07:51:29 UTC 2020
2020-10-09 03:00:30,775 INFO  240    --- [inspectIT] [       Thread-0] rocks.inspectit.ocelot.core.AgentImpl    : OpenCensus was loaded in inspectIT classloader
2020-10-09 03:00:31,845 INFO  1310   --- [inspectIT] [       Thread-0] r.i.o.core.config.InspectitEnvironment   : initializing file based configuration from dir: /inspectit-config
2020-10-09 03:00:31,957 INFO  1422   --- [inspectIT] [       Thread-0] r.i.o.core.config.InspectitEnvironment   : Registered Configuration Sources:
2020-10-09 03:00:31,958 INFO  1423   --- [inspectIT] [       Thread-0] r.i.o.core.config.InspectitEnvironment   :   systemProperties
2020-10-09 03:00:31,958 INFO  1423   --- [inspectIT] [       Thread-0] r.i.o.core.config.InspectitEnvironment   :   systemEnvironment
2020-10-09 03:00:31,959 INFO  1424   --- [inspectIT] [       Thread-0] r.i.o.core.config.InspectitEnvironment   :   fileBasedConfig
2020-10-09 03:00:31,959 INFO  1424   --- [inspectIT] [       Thread-0] r.i.o.core.config.InspectitEnvironment   :   fileBasedConfig/..2020_10_09_01_00_08.725396516/config-a-REST.yaml
2020-10-09 03:00:31,959 INFO  1424   --- [inspectIT] [       Thread-0] r.i.o.core.config.InspectitEnvironment   :   fileBasedConfig/..2020_10_09_01_00_08.725396516/config-b-production-elastisys.yaml
2020-10-09 03:00:31,959 INFO  1424   --- [inspectIT] [       Thread-0] r.i.o.core.config.InspectitEnvironment   :   fileBasedConfig/..2020_10_09_01_00_08.725396516/config-c-common.yaml
2020-10-09 03:00:31,959 INFO  1424   --- [inspectIT] [       Thread-0] r.i.o.core.config.InspectitEnvironment   :   fileBasedConfig/config-a-REST.yaml
2020-10-09 03:00:31,959 INFO  1424   --- [inspectIT] [       Thread-0] r.i.o.core.config.InspectitEnvironment   :   fileBasedConfig/config-b-production-elastisys.yaml
2020-10-09 03:00:31,959 INFO  1424   --- [inspectIT] [       Thread-0] r.i.o.core.config.InspectitEnvironment   :   fileBasedConfig/config-c-common.yaml
2020-10-09 03:00:31,960 INFO  1425   --- [inspectIT] [       Thread-0] r.i.o.core.config.InspectitEnvironment   :   inspectitDefaults
2020-10-09 03:00:31,960 INFO  1425   --- [inspectIT] [       Thread-0] r.i.o.core.config.InspectitEnvironment   :   inspectitEnvironment
```

The configuration is mounted as a ConfigMap in Kubernetes. And InspectIT is reading the configurations twice ConfigMaps are symlinked when mounted. But as I wrote there are 8 other projects that has the same setup without these exceptions.

```
tomcat@tomcat-rest-a-7c7b4657c-gjdhh:/inspectit-config$ ls -lR
.:
total 0
lrwxrwxrwx 1 root root 25 Oct  9 01:28 config-a-REST.yaml -> ..data/config-a-REST.yaml
lrwxrwxrwx 1 root root 41 Oct  9 01:28 config-b-production-elastisys.yaml -> ..data/config-b-production-elastisys.yaml
lrwxrwxrwx 1 root root 27 Oct  9 01:28 config-c-common.yaml -> ..data/config-c-common.yaml
tomcat@tomcat-rest-a-7c7b4657c-gjdhh:/inspectit-config$ ls -la ..data/
total 20
drwxr-sr-x 2 root daemon 4096 Oct  9 01:28 .
drwxrwsrwx 3 root daemon 4096 Oct  9 01:28 ..
-rwxr-xr-x 1 root daemon    4 Oct  9 01:28 config-a-REST.yaml
-rwxr-xr-x 1 root daemon    4 Oct  9 01:28 config-b-production-elastisys.yaml
-rwxr-xr-x 1 root daemon 1875 Oct  9 01:28 config-c-common.yaml
```

# Java
```
$ java -version
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.262-b10, mixed mode)
```

# Tomcat
Docker image: tomcat:9.0.38-jdk8-adoptopenjdk-hotspot

**Comment by JonasKunz** [comment]
Hi @martonsz,

The error you see is caused by inspectit trying to read the [trace correlation headers](https://www.w3.org/TR/trace-context/#tracestate-limits). These are used for propagating trace-IDs for distributed tracing as well as propagating additional meta-data as key-value-pairs. These key-value pairs are sent via the `tracestate` header which seems to be invalid in your case.

The `tracestate` header printed in your example is invalid because the key `420844@nr` contains an `@` which is not an allowed character and does not start with a non-numeric letter. Unfortunately OpenCensus is very strict regarding these rules and therefore throws an exception (which get's caught and printed by inspectIT).

inspectIT itself does not use the `tracestate` header, it however is read and propagated through all services.
This means that the `tracestate` header must come from one of your services, e.g. via a library you use which already includes tracing.

To get rid of the error message you can disable the reading of all trace correlation headers. This reading logic is implemented by a default rule of inspectIT, which you can disable with the following snippet:

```
inspectit:
  instrumentation:
    rules:
      r_servletapi_downPropagation:
        enabled: false
```

However, with this setting distributed tracing will also not work correctly anymore, keep this in mind in case you plan on adding tracing in the future.

**Comment by martonsz** [comment]
It stopped logging errors!

I will look into what libraries what libraries this project has that the others are missing.
I am using Inspecit-ocelot to get Prometheus metrics right now and planning to start trying out the tracing part soon :)

@JonasKunz Than you! 🥇
